<?php

namespace Database\Seeders;

use App\Models\Order;
use App\Models\OrderDetails;
use Illuminate\Database\Seeder;

class OrderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $orders = array(
            array('party_id' => '3','user_id' => '1','merchandiser_id' => '7','bank_id' => NULL,'order_no' => '0000001','title' => 'ooo','image' => NULL,'department' => NULL,'fabrication' => NULL,'gsm' => NULL,'yarn_count' => NULL,'shipment_mode' => NULL,'payment_mode' => NULL,'year' => NULL,'season' => NULL,'description' => NULL,'meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-07-21","expire_date":"2024-07-21","negotiation":null,"loading":null,"discharge":null,"payment_terms":null,"remarks":null}','lc' => '390','status' => '2','created_at' => now(),'updated_at' => now()),
            array('party_id' => '3','user_id' => '1','merchandiser_id' => '15','bank_id' => NULL,'order_no' => '0000002','title' => 'uh','image' => NULL,'department' => NULL,'fabrication' => NULL,'gsm' => NULL,'yarn_count' => NULL,'shipment_mode' => NULL,'payment_mode' => NULL,'year' => NULL,'season' => NULL,'description' => NULL,'meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-07-22","expire_date":"2024-07-22","negotiation":null,"loading":null,"discharge":null,"payment_terms":null,"remarks":null}','lc' => '8100','status' => '2','created_at' => now(),'updated_at' => now()),
            array('party_id' => '6','user_id' => '2','merchandiser_id' => '15','bank_id' => '1','order_no' => '0000003','title' => 'CARGO NR232','image' => NULL,'department' => NULL,'fabrication' => '100%COTTON TWILL AOP','gsm' => '120','yarn_count' => '168x70','shipment_mode' => NULL,'payment_mode' => 'LC','year' => NULL,'season' => '2024','description' => 'LADIES LONG PANT','meta' => '{"pantone":"234-424 TCS"}','invoice_details' => '{"consignee":null,"contact_date":"2024-07-25","expire_date":"2024-08-31","negotiation":null,"loading":null,"discharge":null,"payment_terms":"LC 120 DAYS","remarks":null}','lc' => '110000','status' => '2','created_at' => now(),'updated_at' => now()),
            array('party_id' => '6','user_id' => '8','merchandiser_id' => '15','bank_id' => '1','order_no' => '0000004','title' => 'yhg','image' => NULL,'department' => NULL,'fabrication' => 'oioio','gsm' => '78','yarn_count' => '168','shipment_mode' => NULL,'payment_mode' => NULL,'year' => NULL,'season' => NULL,'description' => 'hjiojo','meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-07-25","expire_date":"2024-07-25","negotiation":null,"loading":null,"discharge":null,"payment_terms":null,"remarks":null}','lc' => '6000','status' => '1','created_at' => now(),'updated_at' => now()),
            array('party_id' => '5','user_id' => '2','merchandiser_id' => '7','bank_id' => '1','order_no' => '0000005','title' => 'POLO 5000 PCS','image' => NULL,'department' => NULL,'fabrication' => 'fsfsdfsfs','gsm' => 'fsf','yarn_count' => 'fefef','shipment_mode' => 'FOB','payment_mode' => 'CASH','year' => '2023','season' => 'fall','description' => 'dsfsf','meta' => '{"pantone":"fefe"}','invoice_details' => '{"consignee":"fefe","contact_date":"2024-07-27","expire_date":"2024-07-27","negotiation":"40","loading":"BD","discharge":"NY","payment_terms":"LC","remarks":null}','lc' => '1320000','status' => '2','created_at' => now(),'updated_at' => now()),
            array('party_id' => '5','user_id' => '4','merchandiser_id' => '15','bank_id' => NULL,'order_no' => '0000006','title' => 'surat','image' => NULL,'department' => NULL,'fabrication' => 'fabric, cotton','gsm' => '90','yarn_count' => '3','shipment_mode' => NULL,'payment_mode' => NULL,'year' => NULL,'season' => NULL,'description' => 'textle check','meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-08-12","expire_date":"2024-08-12","negotiation":null,"loading":null,"discharge":null,"payment_terms":null,"remarks":null}','lc' => '240000','status' => '1','created_at' => now(),'updated_at' => now()),
            array('party_id' => '1','user_id' => '2','merchandiser_id' => '15','bank_id' => NULL,'order_no' => '0000007','title' => 'Polo','image' => NULL,'department' => NULL,'fabrication' => 'Single Jersey','gsm' => '160','yarn_count' => NULL,'shipment_mode' => 'Ship','payment_mode' => 'Cash','year' => '2024','season' => 'Summer','description' => 'Polo','meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-08-12","expire_date":"2024-08-15","negotiation":null,"loading":"Dhaka","discharge":"Dhaka","payment_terms":"Cash","remarks":null}','lc' => '650000','status' => '2','created_at' => now(),'updated_at' => now()),
            array('party_id' => '6','user_id' => '1','merchandiser_id' => '15','bank_id' => NULL,'order_no' => '0000008','title' => 'rr','image' => NULL,'department' => NULL,'fabrication' => NULL,'gsm' => NULL,'yarn_count' => NULL,'shipment_mode' => NULL,'payment_mode' => NULL,'year' => NULL,'season' => NULL,'description' => NULL,'meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-08-15","expire_date":"2024-08-15","negotiation":null,"loading":null,"discharge":null,"payment_terms":null,"remarks":null}','lc' => '1800','status' => '2','created_at' => now(),'updated_at' => now()),
            array('party_id' => '7','user_id' => '8','merchandiser_id' => '15','bank_id' => NULL,'order_no' => 'Aut reprehenderit ve','title' => 'Beatae eos dolor sus','image' => 'uploads/24/08/1724322755.jpg','department' => NULL,'fabrication' => 'Qui commodo et lorem','gsm' => 'Aliquip saepe cupida','yarn_count' => 'Consequatur rerum h','shipment_mode' => 'Et sit vel dicta nu','payment_mode' => 'Rerum enim voluptate','year' => '1990','season' => 'Aliquip dolorem veni','description' => 'Consectetur nihil m','meta' => '{"pantone":"Qui laudantium labo"}','invoice_details' => '{"consignee":"Nostrum quam modi qu","contact_date":"1977-10-22","expire_date":"1989-01-30","negotiation":"At sequi aliqua Omn","loading":"Qui ipsa commodo al","discharge":"Odio dolores ipsam v","payment_terms":"Dolore eiusmod nulla","remarks":"Nostrum aut reiciend"}','lc' => '2298','status' => '1','created_at' => now(),'updated_at' => now()),
            array('party_id' => '7','user_id' => '1','merchandiser_id' => '15','bank_id' => '1','order_no' => '0000010','title' => 'ORDER','image' => NULL,'department' => NULL,'fabrication' => NULL,'gsm' => NULL,'yarn_count' => NULL,'shipment_mode' => NULL,'payment_mode' => NULL,'year' => NULL,'season' => NULL,'description' => 'asdas','meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-08-22","expire_date":"2024-08-22","negotiation":null,"loading":null,"discharge":null,"payment_terms":null,"remarks":null}','lc' => '200','status' => '2','created_at' => now(),'updated_at' => now()),
            array('party_id' => '7','user_id' => '1','merchandiser_id' => '15','bank_id' => '1','order_no' => '0000011','title' => 'bb','image' => NULL,'department' => NULL,'fabrication' => 'bb','gsm' => '12','yarn_count' => '12','shipment_mode' => NULL,'payment_mode' => 'bank','year' => NULL,'season' => NULL,'description' => 'aa','meta' => '{"pantone":null}','invoice_details' => '{"consignee":null,"contact_date":"2024-08-22","expire_date":"2024-08-22","negotiation":null,"loading":"12","discharge":"12","payment_terms":"bank","remarks":null}','lc' => '10000','status' => '2','created_at' => now(),'updated_at' => now())
        );

        $order_details = array(
            array('order_id' => '1','style' => 'iii','color' => 'null','item' => 'ooo','shipment_date' => '2024-07-21','qty' => '5','unit_price' => '12','total_price' => '60','created_at' => '2024-07-22 07:47:58','updated_at' => '2024-07-22 07:47:58'),
            array('order_id' => '1','style' => 'iiii','color' => 'null','item' => 'ooo','shipment_date' => '2024-08-01','qty' => '22','unit_price' => '15','total_price' => '330','created_at' => '2024-07-22 07:47:58','updated_at' => '2024-07-22 07:47:58'),
            array('order_id' => '2','style' => '7100','color' => 'black','item' => NULL,'shipment_date' => '2024-07-22','qty' => '90','unit_price' => '90','total_price' => '8100','created_at' => '2024-07-22 07:51:38','updated_at' => '2024-07-22 07:51:38'),
            array('order_id' => '3','style' => 'CARGO NR232','color' => 'TIGER PRINT','item' => 'LADIES LONG PANT','shipment_date' => '2024-09-20','qty' => '20000','unit_price' => '5.50','total_price' => '110000','created_at' => '2024-07-26 05:31:41','updated_at' => '2024-07-26 05:31:41'),
            array('order_id' => '4','style' => 'hhh','color' => 'ty','item' => NULL,'shipment_date' => '2024-07-25','qty' => '600','unit_price' => '10','total_price' => '6000','created_at' => '2024-07-26 05:45:04','updated_at' => '2024-07-26 05:45:04'),
            array('order_id' => '6','style' => 'eb001','color' => 'red','item' => NULL,'shipment_date' => '2024-08-12','qty' => '2000','unit_price' => '120','total_price' => '240000','created_at' => '2024-08-12 18:37:43','updated_at' => '2024-08-12 18:37:43'),
            array('order_id' => '5','style' => 'POLO','color' => 'Black','item' => 'fsfjkefef','shipment_date' => '2024-07-27','qty' => '10000','unit_price' => '120','total_price' => '1200000','created_at' => '2024-08-14 14:45:14','updated_at' => '2024-08-14 14:45:14'),
            array('order_id' => '5','style' => 'jkjkj','color' => 'white','item' => 'null','shipment_date' => '2024-07-26','qty' => '500','unit_price' => '20','total_price' => '10000','created_at' => '2024-08-14 14:45:14','updated_at' => '2024-08-14 14:45:14'),
            array('order_id' => '5','style' => 'feiewjfmlwef','color' => 'red','item' => 'null','shipment_date' => '2024-07-29','qty' => '5000','unit_price' => '22','total_price' => '110000','created_at' => '2024-08-14 14:45:14','updated_at' => '2024-08-14 14:45:14'),
            array('order_id' => '7','style' => 'POLO','color' => 'blue','item' => 'T-shirt','shipment_date' => '2024-08-12','qty' => '10000','unit_price' => '65','total_price' => '650000','created_at' => '2024-08-18 01:39:03','updated_at' => '2024-08-18 01:39:03'),
            array('order_id' => '9','style' => 'Quaerat aliquip fugi','color' => 'In ex lorem dolorem','item' => 'Sed sunt magni exer','shipment_date' => '2000-02-15','qty' => '4','unit_price' => '562','total_price' => '2248','created_at' => '2024-08-22 22:32:35','updated_at' => '2024-08-22 22:32:35'),
            array('order_id' => '9','style' => 'vx sf','color' => 'Blue','item' => 'w ds sd','shipment_date' => '2024-08-22','qty' => '2','unit_price' => '25','total_price' => '50','created_at' => '2024-08-22 22:32:35','updated_at' => '2024-08-22 22:32:35'),
            array('order_id' => '8','style' => 'teee','color' => 'RED','item' => NULL,'shipment_date' => '2024-08-15','qty' => '40','unit_price' => '45','total_price' => '1800','created_at' => '2024-08-23 03:33:03','updated_at' => '2024-08-23 03:33:03'),
            array('order_id' => '10','style' => 'STYLE 1','color' => 'RED','item' => 'pantalones Azul','shipment_date' => '2024-08-22','qty' => '10','unit_price' => '10','total_price' => '100','created_at' => '2024-08-23 04:45:46','updated_at' => '2024-08-23 04:45:46'),
            array('order_id' => '10','style' => 'STYLE 2','color' => 'BLUE','item' => 'mantendra','shipment_date' => '2024-08-22','qty' => '10','unit_price' => '10','total_price' => '100','created_at' => '2024-08-23 04:45:46','updated_at' => '2024-08-23 04:45:46'),
                
            array('order_id' => '11','style' => '12','color' => 'blak','item' => 't10','shipment_date' => '2024-08-22','qty' => '10','unit_price' => '1000','total_price' => '10000','created_at' => '2024-08-23 05:55:20','updated_at' => '2024-08-23 05:55:20')
        );

        Order::insert($orders);
        OrderDetails::insert($order_details);
    }
}
